config/routes.rb
Rails.application.routes.draw do
devise_for :users

resources :users

resources :blogs do
	resource :blog_comments, only: [:create, :destroy]
	resource :favorites, only: [:create, :destroy]
end

#resources :blog_images, only: [:new, :create, :index, :show]


get 'blogs/search/:id' => 'blogs#show'
root 'blogs#index'




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	acts_as_taggable
	acts_as_taggable_on :categories, :interests
  is_impressionable






	belongs_to :user
	attachment :image
	has_many :blog_comments, dependent: :destroy
	 validates_presence_of :title
	 validates_presence_of :body
	has_many :categories, through: :blog_categories
	has_many :blog_categories, dependent: :destroy

 	def save_categories(tags)
    current_tags = self.categories.pluck(:name) unless self.categories.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.categories.delete Category.find_by(name:old_name)
    end
     # Create new taggings:
    new_tags.each do |new_name|
      article_category = Category.find_or_create_by(name:new_name)
      self.categories << article_category
    end
end
end

app/models/blog_category.rb
class BlogCategory < ApplicationRecord
belongs_to :blog
  belongs_to :category
  validates :blog_id,presence:true
  validates :category_id,presence:true
end

app/models/blog_comment.rb
class BlogComment < ApplicationRecord
	belongs_to :user
	belongs_to :blog
end

app/models/blog_image.rb
class BlogImage < ApplicationRecord
	belongs_to :user
	attachment :image
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name,presence:true,length:{maximum:50}
  has_many :blog, through: :blog_categories
  has_many :blog_categories, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :blog_images
  has_many :blogs
  has_many :blog_comments, dependent: :destroy
  attachment :image
  validates :name, presence: true, uniqueness: true,
  				   length:{ in: 2..20 }
  acts_as_taggable
  is_impressionable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email,:image,:name])
  end
end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController
def create
blog = Blog.find(params[:blog_id])
    comment = current_user.blog_comments.new(blog_comment_params)
    comment.blog_id = blog.id
    comment.save
    redirect_to blogs_path(blog)
end





private
def blog_comment_params
  params.require(:blog_comment).permit(:user_id,:blog_id,:comment)
end

end

app/controllers/blog_images_controller.rb
class BlogImagesController < ApplicationController
def new
end

def create
	
end

def index
end

def show
end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
    @q = Blog.search(params[:q])
    @blogs = @q.result(distinct: true)
    @blogs = Blog.where("created_at not ?",nil)
    #@blog = Blog.order("@blog.impressionable_count ASC")
    @blogs =Blog.order("created_at DESC")
    @ranks = Blog.order('counter DESC').limit(10)
    #@most_viewed = @blog.order('impressionist_count ASC')
  end

  def show
    @blog = Blog.find(params[:id])
    @blog_comment = BlogComment.new
    @page_views = @blog.impressionist_count
    impressionist(@blog, nil, :unique => [:session_hash])
    @blog.increment!(:counter)
  end

  def new
    @blog = Blog.new
    @blog.tag_list.add('awesome' "slick")     # タグを追加
    @blog.tag_list.remove('awesome' "slick")  # タグを削除
  end

  def edit
    @blog = Blog.find(params[:id])
    @blog.tag_list.add('awesome' "slick")     # タグを追加
    @blog.tag_list.remove('awesome' "slick")  # タグを削除
  end

  def create
    blog = Blog.new(blog_params)
    blog.user_id = current_user.id
    blog.save
    redirect_to blogs_path
  end

  def update
    blog = Blog.find(params[:id])
    blog.update(blog_params)
    redirect_to blog_path(blog.id)
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

impressionist actions: [:index, :show]



private
      def blog_params
        params.require(:blog).permit(:title , :body, :image, :tag_list)
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@blogs = @user.blogs
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
    @user.update(user_params)
    redirect_to blogs_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blog_images_helper.rb
module BlogImagesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<h1>編集画面</h1>


<div class="container">
  <div class="row">
    <div class="col-md-12">
    <table class="form_table">
      <%= form_for(@blog) do |f| %>

            <tr>
              <td>画像</td>
              <div class="image-new">
              <td><%= f.attachment_field :image %></td>
              </div>
            </tr>

              <div class="form-group">
                <%= f.label :blog, :tag_list %>
                <%= f.text_field :tag_list, value: @blog.tag_list.join(','), class: "form-control" %>
              </div>

            <tr>
              <td>タイトル</td>
              <td><%= f.text_area :title %></td>
            </tr>

            <tr>
              <td>本文</td>
              <td><%= f.text_area :body %></td>
            </tr>

            <tr>
            <td><%= f.submit '保存' %></td>
            </tr>

        </table>
      <% end %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h4>ようこそ！B.A.Bへ！ここはここはゲーム関連のブログページです！みんなで書いた記事をみんなでコメントし合いましょう</h4>
    </div>
<%= search_form_for(@q, url:blogs_path) do |f| %>
  <%= f.label :title_or_body_cont, "ブログタイトル or ブログ記事" %>
  <%= f.search_field :title_or_body_cont %>
  <%= f.submit %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-8">
      <% @blogs.each do |blog| %>
            <%= attachment_image_tag blog, :image, :fill, 500, 150, format: 'jpeg' %>
              <% blog.tags.each do |tag| %>

                      <h5>タグ名<%= tag.name %></h5>
                    <% end %>
                    <h4>タイトル</h4>
                  <h3><%=link_to blog.title, blog_path(blog.id) %></h3>
                  <h4><%= blog.body %></h4>
                  <h5>閲覧数</h5>
                  <h5><%= blog.counter %></h5>

      <% end %>
    </div>
<div class="container">
 <div class="row">
 <div class="col-xs-4">
  <h2>ランキング</h2>
    <tr>
<td><% @ranks.each_with_index do |blog, i| %>
  第<%= i + 1 %>位:<%=link_to blog.title, blog_path(blog.id) %>
  閲覧数:<%= blog.counter %>
  </td>
</tr>
  <br>
  <br>
  
<% end %>
</div>

<% if user_signed_in? %>
<div class="container">
 <div class="row">
 <div class="col-xs-4">
 <h2>User info</h2>
      <table class="table">
            <tbody>
              <td>name</td>
              <td><%= current_user.name %></td>
            </tr>
            <tr>
              <td>introduction</td>
              <td><%= current_user.introduction %></td>
            </tr>
            <%=link_to "ブログの新規投稿", new_blog_path, class: "btn btn-default active" %>
          </tbody>
      </table>
      <% end %>

<div class="col-xs-10">
<% @blogs.each do |blog| %>
<table class="table">
  <tbody>
    <tr>
  <td>投稿月：<%= blog.created_at %></td>
    </tr>
 </tbody>
</table>
<% end %>

app/views/blogs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
		<table class="form_table">
			<%= form_for(@blog) do |f| %>

						<tr>
							<td>画像</td>
							<div class="image-new">
							<td><%= f.attachment_field :image %></td>
							</div>
						</tr>

      <div class="form-group">
    <%= f.label :blog, :tag_list %>
    <%= f.text_field :tag_list, value: @blog.tag_list.join(','), class: "form-control" %>
  </div>

						<tr>
							<td>タイトル</td>
							<td><%= f.text_area :title %></td>
						</tr>

						<tr>
							<td>本文</td>
							<td><%= f.text_area :body %></td>
						</tr>

						<tr>
						<td><%= f.submit '投稿' %></td>
						</tr>

				</table>
			<% end %>
	</div>
</div>

app/views/blogs/show.html.erb
<div class="container">
    <div class="row">
    <div class="col-xs-8">
<%= attachment_image_tag @blog, :image, :fill, 400, 100, format: 'jpeg' %>
	<h3><%= @blog.title %></h3>
    <h4><%= @blog.body %></h4>
    <div class="float-wrapper">
        <h4 class="comment-count"><%= @blog.blog_comments.count %>件コメント</h4>

            <script type="text/javascript">!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

            <a href="https://twitter.com/share" class="twitter-share-button" data-size="large" data-text="Big Apple Bloger" data-via="" data-dnt="true">Tweet</a>

            <a href="https://twitter.com/USERNAME" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false" data-size="large" data-dnt="true">Follow @USERNAME</a>
    </div>

    <div class="col-xs-6">
        <table class="table">
        <% @blog.blog_comments.each do |blog_comment| %>
                            <tr>
                            <td><%= blog_comment.user.name %>
                            <%= blog_comment.created_at.strftime('%Y/%m/%d') %>
                            <%= blog_comment.comment %>
                        </td>
                    </tr>

        <% end %>
        </table>
    </div>
</div>

        <div class="col-xs-4">
            <h2>投稿者</h2>
                <div><%= attachment_image_tag @user, :image, size: '100x100' %></div>
            <table class="table">
                <tbody>
                    <tr>
                      <th>ニックネーム</th>
                      <th><%= @blog.user.name %></th>
                    </tr>
                    <tr>
                      <th>自己紹介</th>
                      <th><%= @blog.user.introduction %></th>
                    </tr>
                        <% if user_signed_in? %>
                            <% if @blog.user.id == current_user.id %>
                                <%= link_to "記事編集", edit_blog_path(@blog.id), class: "btn btn-default active"%>
                                <%= link_to "記事削除", blog_path(@blog.id), method: :delete, class: "btn btn-default active" %>
                            <% end %>
                        <% end %>
                </tbody>
            </table>
        </div>



<div class="col-xs-8">
<% if user_signed_in? %>
    <%= form_for [@blog, @blog_comment] do |f| %>
        <div class="row">
            <div class="col-sm-12">
                <%= f.text_field :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
            </div>
        </div>
        <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
    <% end %>
<% end %>
</div>

app/views/layouts/_adminHeader.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="logo admin_logo">
        BIG APPLE Bolger admin
      </div>
    </div>
    <div class="col-md-9">
      <div class="row">
        <div class="col-md-12">
          <div class="nav admin-nav">
            <ul>
              <% if admin_signed_in? %>
                <li>ユーザーメールアドレス：<%= current_admin.email %>　　</li>
                <% if request.path != admins_top_path %>
                  <li><%= link_to '　Home',admins_top_path %></li>
                  <li><%= link_to '　ユーザー一覧',admins_users_path %></li>
                <% end %>
                <li><%= link_to '　Sign out',destroy_admin_session_path, method: :delete %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_userHeader.html.erb
<div class="container">
 <div class="row">
   <div class="col-md-3">
      <span class="header_logo_text">Big Apple Bloger</span>
     </div>
     <div class="row">
       <div class="col-md-12">
         <div class="nav user-nav">
           <ul>
             <% if user_signed_in? %>
               <li>Welcome!:　<%= current_user.name%> </li>
               <li><%= link_to '　Home',blogs_path  %></li>
               <li><%= link_to '　My Page',user_path(current_user.id) %></li>
               <li><%= link_to '　Sign out',destroy_user_session_path, method: :delete %></li>
             <% else %>
               <li><%= link_to '　Home',blogs_path %></li>
               <li><%= link_to '　Sign in',new_user_session_path %></li>
               <li><%= link_to '　Sign up',new_user_registration_path %></li>
             <% end %>
           </ul>
         </div>
       </div>
     </div>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header>
      <% if request.path.include?('admin') %>
       <%= render 'layouts/adminHeader' %>
      <% else %>
        <%= render 'layouts/userHeader' %>
      <% end %>
    </header>
    <div class="wrapper">
      <main>
        <%= yield %>
      </main>
      <div class="push"></div>
    </div>
    <footer>
      Copyright © 2018 BIG APPLE Member...is always in your memory
    </footer>
  </body>
</html>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
	<div class="user_box">
<h1 class="user_info"> User edit</h1>
    </div>
		  	<table class="form_table">
		  		<%= form_for(@user) do |f| %>
		  		<tr>
				  <td><%= f.text_area :name %></td>
				</tr>

				<tr>
				  <td><%= f.email_field :email %></td>
				</tr>

				<tr>
				  <td><%= f.attachment_field :image %></td>
				</tr>

				<tr>
				  <td><%= f.text_area :introduction %></td>
				</tr>

		  	</table>
				  	<div class="btn_box1">
				  	<%= f.submit "更新", class: " btn red-btn btn-xs" %>
				    </div>
			    <% end %>

		            <div class="btn_box2">
					   <%= link_to "戻る", user_path(@user.id), class: "btn red-gray-btn btn-xs" %>
					</div>
</div>

app/views/users/show.html.erb
<div class="container">
 <div class="row">
    <div class="col-xs-8">
<% @blogs.each do |blog| %>
  <h2>  記事情報 </h2>
  <tr>
	<td><%= attachment_image_tag blog, :image, :fill, 100, 100, format: 'jpeg' %></td>
    <td><%= blog.title %></td>
    <td><%= blog.body %></td>
  </tr>
  <div class="row">
      		<%= link_to "編集", edit_blog_path(blog.id), class: "btn btn-default active" %>
      		<%= link_to "削除", blog_path(blog.id), class: "btn btn-default active", method: :delete %>
</div>
<% end %>
</div>



<div class="col-xs-4">
  <h2>User Info</h2>
    <table class="table">
      <tbody>
        <tr>
          <td><%= attachment_image_tag @user, :image, :fill, 100, 100, format: 'jpeg' %></td>
        </tr>

        <tr>
        <td><%= @user.email %></td>
        </tr>

        <tr>
          <td><%= @user.name %></td>
        </tr>

        <tr>
          <td><%= @user.introduction %></td>
        </tr>
          <%= link_to 'ユーザー編集' , edit_user_path, class: "btn btn-default active" %>
      </tbody>
    </table>
</div>
</div>
</div>